return {
    token = {
        type = 'identifier',
        characters = {},
    },
    reserved = {
        'and',
        'break',
        'do',
        'else',
        'elseif',
        'end',
        'false',
        'for',
        'function',
        'method',
        'meta',
        'class',
        'extends',
        'goto',
        'label',
        'if',
        'in',
        'local',
        'global',
        'nil',
        'not',
        'or',
        'repeat',
        'return',
        'then',
        'true',
        'until',
        'while',
        'switch',
        'case',
        'default',
        'define',
        'enum'
    }
}