return {
    token = {
        type = 'symbol',
        characters = {},
    },

    symbols = {
        ['..='] = 'join_equal',
        ['...'] = 'dots',
        ['=|='] = 'type_equality',
        ['==='] = 'exact_equality',
        ['!=='] = 'exact_inequality',
        ['~=='] = 'exact_inequality',

        ['<<'] = 'left_shift',
        ['>>'] = 'right_shift',
        ['//'] = 'floor_division',
        ['=='] = 'equality',
        ['~='] = 'inequality',
        ['!='] = 'inequality',
        ['<='] = 'less_equal',
        ['>='] = 'greater_equal',
        ['..'] = 'join',

        ['::'] = 'double_colon',
        ['+='] = 'plus_equal',
        ['-='] = 'minus_equal',
        ['*='] = 'star_equal',
        ['/='] = 'slash_equal',
        ['|='] = 'pipe_equal',
        ['&='] = 'and_equal',
        ['%='] = 'mod_equal',
        ['^='] = 'power_equal',
        ['.='] = 'access_equal',
        ['$='] = 'base_equal',
        ['->'] = 'arrow',
        ['=>'] = 'arrow',
        ['|>'] = 'arrow',

        ['&&'] = 'and',
        ['||'] = 'or',

        ['.'] = 'period',
        [','] = 'comma',
        [':'] = 'colon',
        [';'] = 'semicolon',
        ['?'] = 'question_mark',
        ['!'] = 'bang',
        ['('] = 'open_parenthesis',
        [')'] = 'close_parenthesis',
        ['['] = 'open_bracket',
        [']'] = 'close_bracket',
        ['{'] = 'open_brace',
        ['}'] = 'close_brace',

        ['+'] = 'plus',
        ['-'] = 'minus',
        ['*'] = 'star',
        ['/'] = 'slash',
        ['%'] = 'percent',
        ['^'] = 'caret',
        ['#'] = 'hashtag',
        ['&'] = 'ampersand',
        ['~'] = 'tilde',
        ['|'] = 'pipe',
        ['='] = 'equal',
        ['<'] = 'less',
        ['>'] = 'greater',
        ['$'] = 'base'
    }
}